Support for building on older cmake versions
ledger/ledger pull request #1989
Opened 2021-01-12 13:22 UTC by sanel

Backported python cmake module expects at least cmake 3.7 (requested
by policy), which will break builds on older cmake versions, like 3.5.

This fix will omit python module inclusion for any cmake version less
than 3.7 and the the build will continue without problems.

2021-01-13 02:38 UTC, tbm commented
Which system are you on that doesn't have cmake 3.7?

It seems 3.7 came out in November 2016.

I wonder if it's better to make it explicit that a certain version of cmake is needed.

2021-01-13 04:20 UTC, q3aiml commented
@tbm I agree an explicit minimum version likely makes sense. That said I think this change is reasonable even if certain older cmake versions are considered not officially supported.

@sanel Nitpick, but I would find it more readable to use `VERSION_GREATER_EQUAL` rather than `NOT ... VERSION_LESS`. Something like this:

```if((${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.7.0") AND (${CMAKE_VERSION} VERSION_LESS "3.16.0"))```

What do you think?

2021-01-13 04:28 UTC, tbm commented
> if((${CMAKE_VERSION} VERSION_GREATER_EQUAL "3.7.0") AND (${CMAKE_VERSION} VERSION_LESS "3.16.0"))

That sounds cleaner. @sanel can you update your patch and I'll approve. Thanks

2021-01-13 14:54 UTC, tbm requested changes
can you make the change suggested by @q3aiml

2021-01-13 14:55 UTC, sanel commented
Yes! Thank you for your suggestions :)

2021-01-13 15:05 UTC, sanel commented
Regarding the question for the system without cmake 3.7: cmake 3.5 it is part of Slackware 14.2 and newer version is in the work. Slackware also has community provided packages through [slackbuilds](https://slackbuilds.org/) and the latest Ledger version present out there is 3.1.3.

I presume it can't use the latest Ledger versions because it would have to replace system cmake installation or patch the source code in the fly.

This fix would make it buildable again and the change was small enough it didn't affect Ledger build scripts very much.

2021-01-14 03:18 UTC, tbm commented
> Slackware 14.2 and newer version is in the work

Thanks for the clarification.

2021-01-14 04:04 UTC, tbm commented
Applied, thank you @sanel!

2021-01-14 04:04 UTC, closed without merging