When calculating balance assignments, strip away lot annotations
ledger/ledger pull request #2109
Opened 2022-04-15 19:22 UTC by jwiegley

This allows the following to work:
```
2021/11/22 Entry
    Assets:Foo        100 FOO (Note) {$43.44}
    Income:Bar

2021/11/22 Balance Check
    Assets:Foo                                0 = 100 FOO
```
Without this change, you get an error on the balance check because the lot annotations don't match up.

2022-04-15 19:33 UTC, jwiegley commented
@tbm I already hear you asking for a test in the back of my mind, so I'll have to add that to this PR once I have a moment free, likely in May.

2022-04-16 10:34 UTC, tbm reviewed
The example you posted already works for me (without your patch), so I'm a bit confused.

2022-04-16 21:12 UTC, jwiegley commented
@tbm Then I need a more involved example, that was just my guess at the reduced form.

2022-04-16 21:19 UTC, jwiegley commented
@tbm here is an example that shows the fix:
```
2021/11/22 Entry
    Assets:Foo        100 FOO (Note) {$43.44}
    Income:Bar

2021/11/22 Entry
    Assets:Foo        100 FOO (Misc) {$45.44} = 200 FOO
    Income:Bar

2021/11/22 Entry
    Assets:Foo        $100
    Income:Bar

2021/11/22 Balance Check
    Assets:Foo                                0 FOO = 200 FOO
```

2022-05-02 05:17 UTC, tbm requested changes
John, can you add the example you posted as a testcase.

2022-05-03 20:26 UTC, jwiegley commented
@tbm Added

2022-05-03 20:35 UTC, merged