Minor documentation update - on posting comments and fixed some examples
ledger/ledger pull request #2291
Opened 2023-09-20 13:37 UTC by jstamant

Added to "Transactions and Comments" section 4.7.1 to indicate that posting comments *must* be preceded by at least two spaces.

I also applied this rule consistently to the entire documentation, which only required changes in 4 locations.

I don't think the `ledger` binary cares about spaces in front of posting comments. I never noticed this until I tried using `ledger-mode`'s `ledger-post-edit-amount`, which was causing issues with comments that don't have the proper spacing.

2023-12-06 12:00 UTC, afh requested changes
Happy to approve and merge the proposed consistency changes, once the other review comment below is addressed.

2023-12-07 14:30 UTC, jstamant commented on doc/ledger3.texi
> +at least two whitespace characters.
Yes, I agree with this :+1: 

With some of my own testing, too, it's clear that the ledger binary parses posting notes even when they are **not** preceded by whitespace characters! And the behavior is the same when I tried it with commodities. So I believe the statement made in this suggestion is accurate. :+1:

2023-12-07 14:36 UTC, jstamant reviewed
The suggestion looks good - applied the change and closed the review.

2023-12-07 15:27 UTC, merged

2023-12-07 15:27 UTC, afh commented
Thank you for your contribution @jstamant 🙏